LOAD LABEL test.label2345684 (
    DATA INFILE("hdfs://172.26.92.141:9002/hk/1g.orc")
    INTO TABLE `lineorder_flat_date_orc_import`
    FORMAT AS "orc"
    (LO_ORDERKEY, LO_ORDERDATE, LO_LINENUMBER, LO_CUSTKEY, LO_PARTKEY, LO_SUPPKEY, LO_ORDERPRIORITY , LO_SHIPPRIORITY, LO_QUANTITY, LO_EXTENDEDPRICE , LO_ORDTOTALPRICE , LO_DISCOUNT, LO_REVENUE, LO_SUPPLYCOST, LO_TAX, LO_COMMITDATE, LO_SHIPMODE, C_NAME, C_ADDRESS, C_CITY, C_NATION, C_REGION, C_PHONE, C_MKTSEGMENT, S_NAME, S_ADDRESS, S_CITY, S_NATION, S_REGION, S_PHONE, P_NAME, P_MFGR, P_CATEGORY, P_BRAND, P_COLOR, P_TYPE, P_SIZE, P_CONTAINER)
)
WITH BROKER kks ("username"="user", "password"="password");